    create table anotacao_medica (
        data_hora timestamp(6) not null,
        id_anotacao_medica bigint generated by default as identity,
        id_atendimento bigint not null,
        id_departamento bigint,
        texto_anotacao varchar(255) not null,
        primary key (id_anotacao_medica)
    )
    create table atendimento (
        data_hora timestamp(6) not null,
        departamento_id_departamento bigint,
        id_atendimento bigint generated by default as identity,
        paciente_id_pessoa bigint,
        profissional_id_pessoa bigint,
        recepcionista_id_pessoa bigint,
        motivo varchar(255),
        status varchar(255) not null check (status in ('AGUARDANDO','EM_ATENDIMENTO','FINALIZADO')),
        primary key (id_atendimento)
    )
    create table contato (
        id_contato bigint generated by default as identity,
        id_pessoa bigint,
        telefone varchar(255) not null,
        primary key (id_contato)
    )
    create table departamento (
        id_departamento bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id_departamento)
    )
    create table endereco (
        id_endereco bigint generated by default as identity,
        id_pessoa bigint,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        estado varchar(255),
        logradouro varchar(255) not null,
        numero varchar(255),
        primary key (id_endereco)
    )
    create table especialidade (
        id_especialidade bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id_especialidade)
    )
    create table evolucao_internacao (
        data_hora timestamp(6) not null,
        id_evolucao_internacao bigint generated by default as identity,
        id_internacao bigint not null,
        id_profissional bigint not null,
        texto_evolucao varchar(255) not null,
        primary key (id_evolucao_internacao)
    )
    create table internacao (
        data_entrada timestamp(6) not null,
        data_saida timestamp(6),
        id_atendimento bigint not null unique,
        id_departamento bigint not null,
        id_internacao bigint generated by default as identity,
        id_paciente bigint not null,
        id_profissional bigint not null,
        status varchar(255) not null check (status in ('ATIVA','FINALIZADA')),
        primary key (id_internacao)
    )
    create table paciente (
        id_pessoa bigint not null,
        descricao_medica varchar(255),
        primary key (id_pessoa)
    )
    create table pessoa (
        data_nascimento date not null,
        status_ativo boolean not null,
        id_pessoa bigint generated by default as identity,
        cpf varchar(255) not null unique,
        nome_completo varchar(255) not null,
        primary key (id_pessoa)
    )
    create table profissional (
        id_departamento bigint not null,
        id_pessoa bigint not null,
        primary key (id_pessoa)
    )
    create table recepcionista (
        id_pessoa bigint not null,
        primary key (id_pessoa)
    )
    create table usuario (
        id_pessoa bigint not null,
        email varchar(255) not null,
        senha varchar(255) not null,
        primary key (id_pessoa)
    )
    alter table if exists anotacao_medica 
       add constraint FKmy211u4j265m1pd6ljb5ggdv1 
       foreign key (id_atendimento) 
       references atendimento
    alter table if exists anotacao_medica 
       add constraint FK71uus12fx9mvm4xolagmdg7tx 
       foreign key (id_departamento) 
       references departamento
    alter table if exists atendimento 
       add constraint FK4r3owlaip8iqtobownlys4br4 
       foreign key (departamento_id_departamento) 
       references departamento
    alter table if exists atendimento 
       add constraint FK5gu04edb49md9jhsqpl4nfnl2 
       foreign key (paciente_id_pessoa) 
       references paciente
    alter table if exists atendimento 
       add constraint FKbqb87ghwqlufes7ti1k6ed5d0 
       foreign key (profissional_id_pessoa) 
       references profissional
       add constraint FKes0np7wddnh23avlcvmbq8t37 
       foreign key (recepcionista_id_pessoa) 
       references recepcionista
    alter table if exists contato 
       add constraint FK2h6l5bma9cyyjy8ytvky10n1c 
       foreign key (id_pessoa) 
       references pessoa
    alter table if exists endereco 
       add constraint FK36sv4vy3hi3flqeiswatu14sl 
       foreign key (id_pessoa) 
       references pessoa
    alter table if exists evolucao_internacao 
       add constraint FKrt8yn38mc9gkhamr9qfxhltpl 
       foreign key (id_internacao) 
       references internacao
    alter table if exists evolucao_internacao 
       add constraint FKa8am1thv7meu72l9mtf2wkrh6 
       foreign key (id_profissional) 
       references profissional
    alter table if exists internacao 
       add constraint FKdg7ruukdllhqass6u6dtt4s1r 
       foreign key (id_atendimento) 
       references atendimento
    alter table if exists internacao 
       add constraint FKrxb4xru8b4sx6wdnu8k4ixml1 
       foreign key (id_departamento) 
       references departamento
    alter table if exists internacao 
       add constraint FKh7kefbg0n34fxe8sqy7xdcqgn 
       foreign key (id_paciente) 
       references paciente
    alter table if exists internacao 
       add constraint FK9y1vfbqkxk1sqvxuqtr1ut5be 
       foreign key (id_profissional) 
       references profissional
    alter table if exists paciente 
       add constraint FKr7gw7jr8c8fcg5cdjugjpkp8k 
       foreign key (id_pessoa) 
       references pessoa
    alter table if exists profissional 
       add constraint FKcs9w04hkegg4ipdp5vetfackg 
       foreign key (id_departamento) 
       references departamento
    alter table if exists profissional 
       add constraint FKcj0lj8t351515u94xi7ni7dhj 
       foreign key (id_pessoa) 
       references usuario
    alter table if exists recepcionista 
       add constraint FKifxqecgem932htet0ofdwj6es 
       foreign key (id_pessoa) 
       references usuario
    alter table if exists usuario 
       add constraint FKihpr6fsj9vxc6aqg9seaicql6 
       foreign key (id_pessoa) 
       references pessoa
 