create table anotacao_medica (
    id_anotacao_medica bigint generated by default as identity,
    data_hora timestamp(6) not null,
    texto_anotacao varchar(255) not null,
    id_atendimento bigint not null,
    id_departamento bigint not null,
    primary key (id_anotacao_medica)
);

create table atendimento (
    id_atendimento bigint generated by default as identity,
    data_hora timestamp(6) not null,
    status varchar(255) not null check (status in ('AGUARDANDO','EM_ATENDIMENTO','FINALIZADO')),
    departamento_id_departamento bigint,
    paciente_id_pessoa bigint,
    profissional_id_pessoa bigint,
    recepcionista_id_pessoa bigint,
    primary key (id_atendimento)
);

create table contato (
    id_contato bigint generated by default as identity,
    telefone varchar(255) not null,
    id_pessoa bigint,
    primary key (id_contato)
);

create table departamento (
    id_departamento bigint generated by default as identity,
    nome varchar(255) not null,
    primary key (id_departamento)
);

create table endereco (
    id_endereco bigint generated by default as identity,
    bairro varchar(255),
    cep varchar(255),
    cidade varchar(255),
    estado varchar(255),
    logradouro varchar(255) not null,
    numero varchar(255),
    id_pessoa bigint,
    primary key (id_endereco)
);

create table especialidade (
    id_especialidade bigint generated by default as identity,
    especialidade varchar(255) not null,
    primary key (id_especialidade)
);

    create table evolucao_internacao (
    id_evolucao_internacao bigint generated by default as identity,
    data_hora timestamp(6) not null,
    texto_evolucao varchar(255) not null,
    id_internacao bigint not null,
    id_profissional bigint not null,
    primary key (id_evolucao_internacao)
);

create table internacao (
    id_internacao bigint generated by default as identity,
    data_entrada timestamp(6) not null,
    data_saida timestamp(6),
    status varchar(255) not null check (status in ('ATIVA','FINALIZADA')),
    id_atendimento bigint not null,
    id_departamento bigint not null,
    id_paciente bigint not null,
    id_profissional bigint not null,
    primary key (id_internacao)
);

create table paciente (
    descricao_medica varchar(255),
    id_pessoa bigint not null,
    primary key (id_pessoa)
);

create table pessoa (
    id_pessoa bigint generated by default as identity,
    cpf varchar(255) not null,
    data_nascimento date not null,
    nome_completo varchar(255) not null,
    status_ativo boolean not null,
    primary key (id_pessoa)
);

create table profissional (
    id_pessoa bigint not null,
    id_especialidade bigint not null,
    primary key (id_pessoa)
);

create table recepcionista (
    id_pessoa bigint not null,
    primary key (id_pessoa)
);

create table usuario (
    email varchar(255) not null,
    senha varchar(255) not null,
    id_pessoa bigint not null,
    primary key (id_pessoa)
);