
CREATE TABLE pessoa (
    id_pessoa bigint GENERATED BY DEFAULT AS IDENTITY,
    nome_completo varchar(255) NOT NULL,
    cpf varchar(14) NOT NULL UNIQUE, 
    data_nascimento date NOT NULL,
    status_ativo boolean NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id_pessoa)
);

CREATE TABLE contato (
    id_contato bigint GENERATED BY DEFAULT AS IDENTITY,
    id_pessoa bigint,
    telefone varchar(20) NOT NULL,
    PRIMARY KEY (id_contato),
    CONSTRAINT fk_contato_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE endereco (
    id_endereco bigint GENERATED BY DEFAULT AS IDENTITY,
    id_pessoa bigint,
    logradouro varchar(255) NOT NULL,
    numero varchar(20),
    bairro varchar(255),
    cidade varchar(255),
    estado varchar(2),
    cep varchar(10),
    PRIMARY KEY (id_endereco),
    CONSTRAINT fk_endereco_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE paciente (
    id_pessoa bigint NOT NULL,
    descricao_medica varchar(255),
    PRIMARY KEY (id_pessoa),
    CONSTRAINT fk_paciente_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE usuario (
    id_pessoa bigint NOT NULL,
    email varchar(255) NOT NULL UNIQUE, 
    senha varchar(255) NOT NULL,
    PRIMARY KEY (id_pessoa),
    CONSTRAINT fk_usuario_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE departamento (
    id_departamento bigint GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(255) NOT NULL,
    PRIMARY KEY (id_departamento)
);

CREATE TABLE especialidade (
    id_especialidade bigint GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(255) NOT NULL,
    PRIMARY KEY (id_especialidade)
);

CREATE TABLE profissional (
    id_pessoa bigint NOT NULL,
    id_departamento bigint NOT NULL,
    PRIMARY KEY (id_pessoa),
    CONSTRAINT fk_profissional_usuario FOREIGN KEY (id_pessoa) REFERENCES usuario(id_pessoa),
    CONSTRAINT fk_profissional_departamento FOREIGN KEY (id_departamento) REFERENCES departamento(id_departamento)
);

CREATE TABLE recepcionista (
    id_pessoa bigint NOT NULL,
    PRIMARY KEY (id_pessoa),
    CONSTRAINT fk_recepcionista_usuario FOREIGN KEY (id_pessoa) REFERENCES usuario(id_pessoa)
);

CREATE TABLE atendimento (
    id_atendimento bigint GENERATED BY DEFAULT AS IDENTITY,
    data_hora timestamp(6) NOT NULL,
    motivo varchar(255),
    status varchar(50) NOT NULL,
    paciente_id_pessoa bigint,
    profissional_id_pessoa bigint,
    recepcionista_id_pessoa bigint,
    departamento_id_departamento bigint,
    PRIMARY KEY (id_atendimento),
    CONSTRAINT chk_atendimento_status CHECK (status IN ('AGUARDANDO','EM_ATENDIMENTO','FINALIZADO')),
    CONSTRAINT fk_atendimento_paciente FOREIGN KEY (paciente_id_pessoa) REFERENCES paciente(id_pessoa),
    CONSTRAINT fk_atendimento_profissional FOREIGN KEY (profissional_id_pessoa) REFERENCES profissional(id_pessoa),
    CONSTRAINT fk_atendimento_recepcionista FOREIGN KEY (recepcionista_id_pessoa) REFERENCES recepcionista(id_pessoa),
    CONSTRAINT fk_atendimento_departamento FOREIGN KEY (departamento_id_departamento) REFERENCES departamento(id_departamento)
);

CREATE TABLE anotacao_medica (
    id_anotacao_medica bigint GENERATED BY DEFAULT AS IDENTITY,
    data_hora timestamp(6) NOT NULL,
    texto_anotacao varchar(255) NOT NULL,
    id_atendimento bigint NOT NULL,
    id_departamento bigint,
    PRIMARY KEY (id_anotacao_medica),
    CONSTRAINT fk_anotacao_atendimento FOREIGN KEY (id_atendimento) REFERENCES atendimento(id_atendimento),
    CONSTRAINT fk_anotacao_departamento FOREIGN KEY (id_departamento) REFERENCES departamento(id_departamento)
);

CREATE TABLE internacao (
    id_internacao bigint GENERATED BY DEFAULT AS IDENTITY,
    id_atendimento bigint NOT NULL UNIQUE, 
    id_paciente bigint NOT NULL,
    id_profissional bigint NOT NULL,
    id_departamento bigint NOT NULL,
    data_entrada timestamp(6) NOT NULL,
    data_saida timestamp(6),
    status varchar(50) NOT NULL,
    PRIMARY KEY (id_internacao),
    CONSTRAINT chk_internacao_status CHECK (status IN ('ATIVA','FINALIZADA')),
    CONSTRAINT chk_internacao_datas CHECK (data_saida IS NULL OR data_saida >= data_entrada),
    CONSTRAINT fk_internacao_atendimento FOREIGN KEY (id_atendimento) REFERENCES atendimento(id_atendimento),
    CONSTRAINT fk_internacao_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id_pessoa),
    CONSTRAINT fk_internacao_profissional FOREIGN KEY (id_profissional) REFERENCES profissional(id_pessoa),
    CONSTRAINT fk_internacao_departamento FOREIGN KEY (id_departamento) REFERENCES departamento(id_departamento)
);

CREATE TABLE evolucao_internacao (
    id_evolucao_internacao bigint GENERATED BY DEFAULT AS IDENTITY,
    data_hora timestamp(6) NOT NULL,
    texto_evolucao varchar(255) NOT NULL,
    id_internacao bigint NOT NULL,
    id_profissional bigint NOT NULL,
    PRIMARY KEY (id_evolucao_internacao),
    CONSTRAINT fk_evolucao_internacao FOREIGN KEY (id_internacao) REFERENCES internacao(id_internacao),
    CONSTRAINT fk_evolucao_profissional FOREIGN KEY (id_profissional) REFERENCES profissional(id_pessoa)
);

CREATE INDEX idx_pessoa_nome ON pessoa(nome_completo);
CREATE INDEX idx_pessoa_cpf ON pessoa(cpf);

CREATE INDEX idx_atendimento_data ON atendimento(data_hora);
CREATE INDEX idx_atendimento_paciente ON atendimento(paciente_id_pessoa);
CREATE INDEX idx_atendimento_profissional ON atendimento(profissional_id_pessoa);

CREATE INDEX idx_internacao_paciente ON internacao(id_paciente);
CREATE INDEX idx_internacao_status ON internacao(status);


CREATE OR REPLACE VIEW vw_detalhes_paciente AS
SELECT 
    p.id_pessoa,
    p.nome_completo,
    p.cpf,
    p.data_nascimento,
    pac.descricao_medica,
    c.telefone,
    e.cidade,
    e.estado
FROM pessoa p
JOIN paciente pac ON p.id_pessoa = pac.id_pessoa
LEFT JOIN contato c ON p.id_pessoa = c.id_pessoa
LEFT JOIN endereco e ON p.id_pessoa = e.id_pessoa;

CREATE OR REPLACE VIEW vw_agenda_atendimentos AS
SELECT 
    a.id_atendimento,
    a.data_hora,
    a.status,
    p_pac.nome_completo AS nome_paciente,
    p_prof.nome_completo AS nome_profissional,
    d.nome AS departamento
FROM atendimento a
JOIN pessoa p_pac ON a.paciente_id_pessoa = p_pac.id_pessoa
JOIN pessoa p_prof ON a.profissional_id_pessoa = p_prof.id_pessoa
LEFT JOIN departamento d ON a.departamento_id_departamento = d.id_departamento;